---
title: "Politik"
description: |
  Some additional details about the website
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
### um das an die seiten anzupassen {r, layout="l-body-outset", fig.width=6, fig.height=1.5}

library(tidyverse)
library(dplyr)
library(plotly)
library(lubridate)
library(stringr)
library(ggthemes)
library(extrafont)
library(ggiraph)
library(scales)
library(cowplot)
library(png)
library(grid)
library(forcats)
library(ggforce)
library(ggparliament)

```


Hier kommt noch ein Einleitungstext hin. Hallo ich bin ein Einleitungstext. Hallo hallo hallo. text text text.



# Zeitliche Entwicklung. \nSitze von Frauen in Parlamenten

```{r}
seats <- read.csv("data/raw/before_clean_seats_parliaments.csv", check.names = F) %>%  
            filter(country != "") %>% 
            pivot_longer(cols = -country, names_to = "year", values_to = "n") %>% 
            mutate_if(is.numeric, round) %>% 
            filter(n != "NA") %>% 
            filter(!country %in% c("Africa Eastern and Southern",
                                   "Africa Western and Central",
                                   "Arab World",
                                   "Central Europe and the Baltics",
                                   "Caribbean small states",
                                   "Early-demographic dividend",
                                   "East Asia & Pacific",
                                   "East Asia & Pacific (excluding high income)",
                                   "East Asia & Pacific (IDA & IBRD)",
                                   "Euro area",
                                   "Europe & Central Asia",
                                   "Europe & Central Asia (excluding high income)",
                                   "Europe & Central Asia (IDA & IBRD)",
                                   "European Union",
                                   "Fragile and conflict affected situations",
                                   "Heavily indebted poor countries (HIPC)",
                                   "High income",
                                   "IBRD only",
                                   "IDA & IBRD total",
                                   "IDA blend",
                                   "IDA only",
                                   "IDA total",
                                   "Late-demographic dividend",
                                   "Latin America & Caribbean",
                                   "Latin America & Caribbean (excluding high income)",
                                   "Latin America & Caribbean (IDA & IBRD)",
                                   "Least developed countries: UN classification",
                                   "Low & middle income",
                                   "Low income",
                                   "Lower middle income",
                                   "Middle East & North Africa",
                                   "Middle East & North Africa (excluding high income)",
                                   "Middle East & North Africa (IDA & IBRD)",
                                   "Middle income",
                                   "North America",
                                   "OECD members",
                                   "Other small states",
                                   "Pacific island small states",
                                   "Post-demographic dividend",
                                   "Pre-demographic dividend",
                                   "Small states",
                                   "South Asia",
                                   "South Asia (IDA & IBRD)",
                                   "Sub-Saharan Africa",
                                   "Sub-Saharan Africa (excluding high income)",
                                   "Sub-Saharan Africa (IDA & IBRD)",
                                   "Upper middle income",
                                   "World")) %>% 
            rename(percentage_women = n) %>% 
            mutate(year = as.numeric(year)) %>% 
            group_by(year) %>% 
            mutate(percentage_men = 100 - percentage_women) %>% 
            mutate(percentage = 100) %>% 
            mutate(mean_w = mean(percentage_women)) %>% 
            mutate(mean_m = mean(percentage_men))

#options(digits = 0)



## hier müssen noch infos oder erklärungen folgen wie man von dem datensatz auf den anderen kommt


seats_world <- read.csv("data/to_work_with/barplot_data.csv") %>% na.omit() %>%  rename(Jahr = year)

seats_world$Anteil[seats_world$Anteil == "Frau"] <- "weiblich"
seats_world$Anteil[seats_world$Anteil == "Mann"] <- "männlich"
seats_world$Anteil <- factor(seats_world$Anteil, levels = c("männlich", "weiblich"))

img1 <- readPNG("png_bilder/man.png")
g1 <- rasterGrob(img1, interpolate=FALSE)
img2 <- readPNG("png_bilder/woman.png")
g2 <- rasterGrob(img2, interpolate=FALSE)



# visualisierung
seats_world %>% 
  ggplot() +
  aes(Jahr, fill = Anteil, text = as.character(seats_world$percent)) +
  geom_bar(
    position = position_stack(reverse = F)
  ) +
  scale_x_continuous(
    breaks = c(1997, 2020)
  ) +
  scale_y_continuous(
    labels = label_percent(scale = 1, suffix = " %"),
    expand = c(0,3)
  ) +
  scale_fill_manual(values = c("#CBECFF", "#C21614")) +
  theme_minimal_hgrid(
    line_size = 1,
    color = "transparent"
  ) +
  theme(
    axis.line.x = element_line(size = 1, arrow = arrow()),
    legend.title = element_blank(),
    legend.position = "none",
    axis.text.x = element_text(size = 16, vjust = 0),
    axis.text.y = element_text(size = 13, vjust = 0.5)
  ) +
  geom_hline(yintercept = 50, size = 1) +
  #geom_hline(yintercept = 0, size = 0.3, alpha = 0.5) +
  #geom_hline(yintercept = 25, size = 0.3, alpha = 0.5) +
  #geom_hline(yintercept = 75, size = 0.3, alpha = 0.5) +
  #geom_hline(yintercept = 100, size = 0.3, alpha = 0.5) +
  labs(y = NULL, x = NULL) +
  annotation_custom(g1, xmin = 1997, xmax = 2007, ymin = 15, ymax = 105) +
  annotation_custom(g2, xmin = 2017.5, xmax = 2020.5, ymin = -3, ymax = 25) +
  NULL

```


# Hier jetzt was mit Europa

```{r, layout="l-body-outset", fig.width=6, fig.height=6*0.618}


seats_europe <- read.csv("data/raw/before_clean_seats_parliaments.csv", check.names = F) %>%  
            filter(country != "") %>% 
            pivot_longer(cols = -country, names_to = "year", values_to = "n") %>% 
            mutate_if(is.numeric, round) %>% 
            filter(n != "NA") %>% 
            filter(!country %in% c("Africa Eastern and Southern",
                                   "Africa Western and Central",
                                   "Arab World",
                                   "Central Europe and the Baltics",
                                   "Caribbean small states",
                                   "Early-demographic dividend",
                                   "East Asia & Pacific",
                                   "East Asia & Pacific (excluding high income)",
                                   "East Asia & Pacific (IDA & IBRD)",
                                   "Euro area",
                                   "Europe & Central Asia",
                                   "Europe & Central Asia (excluding high income)",
                                   "Europe & Central Asia (IDA & IBRD)",
                                   "European Union",
                                   "Fragile and conflict affected situations",
                                   "Heavily indebted poor countries (HIPC)",
                                   "High income",
                                   "IBRD only",
                                   "IDA & IBRD total",
                                   "IDA blend",
                                   "IDA only",
                                   "IDA total",
                                   "Late-demographic dividend",
                                   "Latin America & Caribbean",
                                   "Latin America & Caribbean (excluding high income)",
                                   "Latin America & Caribbean (IDA & IBRD)",
                                   "Least developed countries: UN classification",
                                   "Low & middle income",
                                   "Low income",
                                   "Lower middle income",
                                   "Middle East & North Africa",
                                   "Middle East & North Africa (excluding high income)",
                                   "Middle East & North Africa (IDA & IBRD)",
                                   "Middle income",
                                   "North America",
                                   "OECD members",
                                   "Other small states",
                                   "Pacific island small states",
                                   "Post-demographic dividend",
                                   "Pre-demographic dividend",
                                   "Small states",
                                   "South Asia",
                                   "South Asia (IDA & IBRD)",
                                   "Sub-Saharan Africa",
                                   "Sub-Saharan Africa (excluding high income)",
                                   "Sub-Saharan Africa (IDA & IBRD)",
                                   "Upper middle income",
                                   "World")) %>% 
            filter(country %in% c("Albania",
                                  "Andorra",
                                  "Austria",
                                  "Azerbaijan",
                                  "Belarus",
                                  "Belgium",
                                  "Bosnia and Herzegovina",
                                  "Bulgaria",
                                  "Czech Republic",
                                  "Denmark",
                                  "Germany",
                                  "Croatia",
                                  "Cyprus",
                                  "Estonia",
                                  "France",
                                  "Finland",
                                  "Georgia",
                                  "Greece",
                                  "Hungary",
                                  "Iceland",
                                  "Ireland",
                                  "Italy",
                                  "Kazakhstan",
                                  "Latvia",
                                  "Liechtenstein",
                                  "Lithuania",
                                  "Luxembourg",
                                  "Malta",
                                  "Moldova",
                                  "Monaco",
                                  "Montenegro",
                                  "Netherlands",
                                  "North Macedonia",
                                  "Norway",
                                  "Poland",
                                  "Portugal",
                                  "Romania",
                                  "Russian Federation",
                                  "San Marino",
                                  "Serbia",
                                  "Slovak Republic",
                                  "Slovenia",
                                  "Spain",
                                  "Sweden",
                                  "Switzerland",
                                  "Turkey",
                                  "Ukraine",
                                  "United Kingdom"
                                  )
                   ) %>% 
            rename(percentage_women = n) %>% 
            mutate(year = as.numeric(year)) %>% 
            group_by(year) %>% 
            mutate(percentage_men = 100 - percentage_women) %>% 
            mutate(percentage = 100) %>% 
            mutate(mean_w = mean(percentage_women)) %>% 
            mutate(mean_m = mean(percentage_men))



#options(digits = 0)

# englische Ländernamen ins Deutsche
seats_europe$country[seats_europe$country == "Albania"] <- "Albanien"
seats_europe$country[seats_europe$country == "Austria"] <- "Österreich"
seats_europe$country[seats_europe$country == "Azerbaijan"] <- "Aserbaidschan"
seats_europe$country[seats_europe$country == "Belgium"] <- "Belgien"
seats_europe$country[seats_europe$country == "Bosnia and Herzegovina"] <- "Bosnien und Herzegowina"
seats_europe$country[seats_europe$country == "Bulgaria"] <- "Bulgarien"
seats_europe$country[seats_europe$country == "Croatia"] <- "Kroatien"
seats_europe$country[seats_europe$country == "Cyprus"] <- "Zypern"
seats_europe$country[seats_europe$country == "Czech Republic"] <- "Tschechien"
seats_europe$country[seats_europe$country == "Denmark"] <- "Dänemark"
seats_europe$country[seats_europe$country == "Estonia"] <- "Estland"
seats_europe$country[seats_europe$country == "Finland"] <- "Finnland"
seats_europe$country[seats_europe$country == "France"] <- "Frankreich"
seats_europe$country[seats_europe$country == "Georgia"] <- "Georgien"
seats_europe$country[seats_europe$country == "Germany"] <- "Deutschland"
seats_europe$country[seats_europe$country == "Greece"] <- "Griechenland"
seats_europe$country[seats_europe$country == "Hungary"] <- "Ungarn"
seats_europe$country[seats_europe$country == "Iceland"] <- "Island"
seats_europe$country[seats_europe$country == "Ireland"] <- "Irland"
seats_europe$country[seats_europe$country == "Italy"] <- "Italien"
seats_europe$country[seats_europe$country == "Kazakhstan"] <- "Kasachstan"
seats_europe$country[seats_europe$country == "Latvia"] <- "Lettland"
seats_europe$country[seats_europe$country == "Lithuania"] <- "Litauen"
seats_europe$country[seats_europe$country == "Luxembourg"] <- "Luxemburg"
seats_europe$country[seats_europe$country == "Moldova"] <- "Moldau"
seats_europe$country[seats_europe$country == "Netherlands"] <- "Niederlande"
seats_europe$country[seats_europe$country == "North Macedonia"] <- "Nordmazedonien"
seats_europe$country[seats_europe$country == "Norway"] <- "Norwegen"
seats_europe$country[seats_europe$country == "Poland"] <- "Polen"
seats_europe$country[seats_europe$country == "Romania"] <- "Rumänien"
seats_europe$country[seats_europe$country == "Russian Federation"] <- "Russland"
seats_europe$country[seats_europe$country == "Serbia"] <- "Serbien"
seats_europe$country[seats_europe$country == "Slovenia"] <- "Slowenien"
seats_europe$country[seats_europe$country == "Spain"] <- "Spanien"
seats_europe$country[seats_europe$country == "Sweden"] <- "Schweden"
seats_europe$country[seats_europe$country == "Switzerland"] <- "Schweiz"
seats_europe$country[seats_europe$country == "Turkey"] <- "Türkei"
seats_europe$country[seats_europe$country == "United Kingdom"] <- "Großbritannien"
seats_europe$country[seats_europe$country == "Slovak Republic"] <- "Slowakei"




# herausfinden, welche werte die gesamte welt im durchschnitt widerspiegeln. das sind die werte, die man oben im balkendiagramm als weibliche balken gesehen hat
# einen datensatz generieren, der die mittlewerte der gesamten welt darstellen. dabei ist es egal, welches land man konkret auswählt, da alle werte gleich sind (stellt ja den mean über die ganze welt dar)
seats_world_mean <- seats %>% filter(country == "France") %>% select(country, year, mean_w)

# mean_w sind diese werte. diese werden nun manuell an den bisherigen datensatz angefügt

# rename(percentage_women = mean_w, mean_w = percentage_women)
# achtung percentage_women und mean_w musste vertauscht werden, damit percentage_women unten in den plot passt. die daten entsprechen aber der früheren mean_w spalte
# wenn man diesen und den europe datensatz mit full_join zusammengefügt hätte, wäre es zwar einfacher gewesen, jedoch haben dann die prozentwere der "gesamten Welt" etliche Nachkommastellen gehabt (warum auch immer). daher die händische manuelle vorgehensweise
# europe mit "gesamte welt" ergänzen

europe_final <- seats_europe %>% ungroup() %>% 
  add_row(country = "gesamte Welt", year = 1997, percentage_women = 10) %>% 
  add_row(country = "gesamte Welt", year = 1998, percentage_women = 11) %>% 
  add_row(country = "gesamte Welt", year = 1999, percentage_women = 11) %>% 
  add_row(country = "gesamte Welt", year = 2000, percentage_women = 12) %>% 
  add_row(country = "gesamte Welt", year = 2001, percentage_women = 12) %>% 
  add_row(country = "gesamte Welt", year = 2002, percentage_women = 14) %>% 
  add_row(country = "gesamte Welt", year = 2003, percentage_women = 14) %>% 
  add_row(country = "gesamte Welt", year = 2004, percentage_women = 14) %>% 
  add_row(country = "gesamte Welt", year = 2005, percentage_women = 15) %>% 
  add_row(country = "gesamte Welt", year = 2006, percentage_women = 16) %>% 
  add_row(country = "gesamte Welt", year = 2007, percentage_women = 17) %>% 
  add_row(country = "gesamte Welt", year = 2008, percentage_women = 17) %>% 
  add_row(country = "gesamte Welt", year = 2009, percentage_women = 17) %>% 
  add_row(country = "gesamte Welt", year = 2010, percentage_women = 17) %>% 
  add_row(country = "gesamte Welt", year = 2011, percentage_women = 18) %>% 
  add_row(country = "gesamte Welt", year = 2012, percentage_women = 19) %>% 
  add_row(country = "gesamte Welt", year = 2013, percentage_women = 20) %>% 
  add_row(country = "gesamte Welt", year = 2014, percentage_women = 20) %>% 
  add_row(country = "gesamte Welt", year = 2015, percentage_women = 21) %>% 
  add_row(country = "gesamte Welt", year = 2016, percentage_women = 21) %>% 
  add_row(country = "gesamte Welt", year = 2017, percentage_women = 21) %>% 
  add_row(country = "gesamte Welt", year = 2018, percentage_women = 22) %>% 
  add_row(country = "gesamte Welt", year = 2019, percentage_women = 23) %>% 
  add_row(country = "gesamte Welt", year = 2020, percentage_women = 24) %>% 
    group_by(year)




#group by year

order <- c("gesamte Welt", "Albanien", "Andorra", "Aserbaidschan", "Belarus", "Belgien", "Bosnien und Herzegowina", "Bulgarien", "Dänemark", "Deutschland", "Estland", "Finnland", "Frankreich", "Georgien", "Griechenland", "Großbritannien", "Irland", "Island", "Italien", "Kasachstan", "Kroatien", "Lettland", "Liechtenstein", "Litauen", "Luxemburg", "Malta", "Moldau", "Monaco", "Montenegro", "Niederlande", "Nordmazedonien", "Norwegen", "Österreich", "Polen", "Portugal", "Rumänien", "Russland", "San Marino", "Schweden", "Schweiz", "Serbien", "Slowakei", "Slowenien", "Spanien", "Tschechien", "Türkei", "Ukraine", "Ungarn", "Zypern")

colors <- c("red", "#F00101", "#10008C", "#B8413F", "#B10019", "#FABA00", "#212F84", "#0F8063", "#B00F16", "#000000", "#0A63AC", "#084D85", "#D1A7A7", "#FF403D",  "#ABB6CC", "#162360", "#16A64D", "#163AAB", "#AD0243", "#49A7C9", "#DB2500", "#951C46", "#001078", "#C48E04", "#6E94CC", "#B83E31", "#E3B600", "#E23400", "#BA3400", "#FF8900", "#DB2000", "#8D10DB", "#DB7E97", "#DB49A3", "#304900", "#5B4968", "#864085", "#85BCED", "#EBC496", "#FF564F", "#CC445E", "#3733D9", "#3768D9", "#BA1111", "#179B96", "#D61871", "#1619FE", "#02B538", "#FFD966")


spaghetti <- europe_final %>% 
  ggplot() +
  aes(year, percentage_women, color = fct_relevel(country, order)) +
  geom_line() +
  geom_point(
    aes(x = year,
        y = percentage_women,
        text = paste0(
          country, " (", year, ")",
          "\nFrauen im Parlament: ", percentage_women, " %"))) +
  scale_y_continuous(limits = c(0, 50),
                     labels = label_percent(scale = 1, suffix = " %"),
                     expand = c(0,3)) +
  scale_x_continuous(
    limits = c(1997, 2020),
    breaks = c(1997, 2020)) +
  scale_color_manual(values = colors) +
  geom_hline(yintercept = 0, size = 0.3, alpha = 0.3) +
  geom_hline(yintercept = 10, size = 0.3, alpha = 0.3) +
  geom_hline(yintercept = 20, size = 0.3, alpha = 0.3) +
  geom_hline(yintercept = 30, size = 0.3, alpha = 0.3) +
  geom_hline(yintercept = 40, size = 0.3, alpha = 0.3) +
  geom_hline(yintercept = 50, size = 0.3, alpha = 0.3) +
  labs(x = NULL, y = NULL) +
  theme_base() +
  theme() +
  guides(color = guide_legend(""))


font <- list(
  family = "Roboto",
  size = 15,
  color = "#282828"
)

box <- list(
  bgcolor = c("#dddddd"),
  bordercolor = "transparent",
  font = font
)


spaghetti %>%
  ggplotly(tooltip = "text") %>% 
  style(hoverlabel = box) %>% 
  layout(font = font, 
         yaxis = list(fixedrange = TRUE), 
         xaxis = list(fixedrange = TRUE),
         showlegend = T) %>% 
  config(displayModeBar = FALSE)

```

# Hier dann was zur Entwicklung des Bundestages

```{r, layout="l-body-outset", fig.width=9, fig.height=9*0.618}

# datensatz
# selbst generierter Datensatz aus Wikipedia Tabelle (https://de.wikipedia.org/wiki/Frauenanteil_im_Deutschen_Bundestag_seit_1949)
# datensatz zeigt die anzahl/prozente von männern und frauen in den bundestagen an


bundestag_raw <- read.csv("data/to_work_with/bundestagzusammensetzung.csv") %>% 
                  mutate(maenner_anzahl = (mitglieder-frauen_anzahl),
                          maenner_perc = (100-frauen_perc)) %>% 
                  mutate(mitglieder = as.numeric(mitglieder))


bundestag_ds <- bundestag_raw[c(1,2,3,7,6,4,5)] %>%          #variablen in eine sinnvolle reihenfolge bringen
  filter(wahlperiode == "beginn")                         #wir beziehen uns nur auf den beginn der wahlperioden

# ordinale variable für bundestag
scale.bundestag <- c("1. Bundestag 1949-1953",
                     "2. Bundestag 1953-1957",
                     "3. Bundestag 1957-1961",
                     "4. Bundestag 1961-1965",
                     "5. Bundestag 1965-1969",
                     "6. Bundestag 1969-1972",
                     "7. Bundestag 1972-1976",
                     "8. Bundestag 1976-1980",
                     "9. Bundestag 1980-1983",
                     "10. Bundestag 1983-1987",
                     "11. Bundestag 1987-1990",
                     "12. Bundestag 1990-1994",
                     "13. Bundestag 1994-1998",
                     "14. Bundestag 1998-2002",
                     "15. Bundestag 2002-2005",
                     "16. Bundestag 2005-2009",
                     "17. Bundestag 2009-2013",
                     "18. Bundestag 2013-2017",
                     "19. Bundestag 2017-2021",
                     "20. Bundestag 2021"
                     )

bundestag_ds$bundestag <- ordered(bundestag_ds$bundestag, levels = scale.bundestag)
#options(digits = 2)

# https://www.bundestag.de/parlament/plenum/sitzverteilung_20wp
# https://www.bundestag.de/datenhandbuch
# für den verlauf aller bundestage nehme ich die wikipedia tabelle
# für den aktuellen bundestag kann ich die aktuelle seite des bundestages nehmen


# modifizieren datensatz um mit geom point einzelne punkte herausstellen zu können

bundestag_point_w <- bundestag_ds %>% 
  select(bundestag, frauen_anzahl, mitglieder) %>% 
  filter(bundestag %in% c("1. Bundestag 1949-1953",
                          "18. Bundestag 2013-2017",
                          "20. Bundestag 2021"))

bundestag_point_m <- bundestag_ds %>% 
  select(bundestag, maenner_anzahl, mitglieder) %>% 
  filter(bundestag %in% c("1. Bundestag 1949-1953",
                          "20. Bundestag 2021"))



bundestag_ds %>% 
  ggplot() +
  geom_hline(yintercept = 0, size = 0.3, alpha = 0.3) +
  geom_hline(yintercept = 200, size = 0.3, alpha = 0.3) +
  geom_hline(yintercept = 400, size = 0.3, alpha = 0.3) +
  geom_hline(yintercept = 600, size = 0.3, alpha = 0.3) +
  geom_hline(yintercept = 800, size = 0.3, alpha = 0.3) +
  
  #alle abgeordnete
  geom_line(
    aes(y = mitglieder, x = bundestag,  group = 1),
    size = 1.5,
    color = "black"
  ) +
  geom_point(
    data = bundestag_point_m, aes(y = mitglieder, x = bundestag),
    size = 5,
    color = "black"
  ) +
  
  
  #männer
  geom_line(
    aes(y = maenner_anzahl, x = bundestag, group = 1),
    size = 1.5,
    color = "#E62200" #rote linie
  ) +
  geom_point(
    data = bundestag_point_m, aes(y = maenner_anzahl, x = bundestag),
    size = 5,
    color = "#E62200"
  ) +
  
  
  # frauen
  geom_line(
    aes(y = frauen_anzahl, x = bundestag, group = 1),
    size = 1.5,
    color = "#FFB813" #goldene linie
  ) +
  geom_point(
    data = bundestag_point_w, aes(y = frauen_anzahl, x = bundestag),
    size = 5,
    color = "#FFB813" #gold
  ) +


  # appearance
  scale_x_discrete(
    breaks = c("1. Bundestag 1949-1953", "20. Bundestag 2021"),
    expand = c(0,3))+
  scale_y_continuous(
    limits = c(0, 800),
    breaks = c(0, 200, 400, 600, 800),
    expand = c(0.05,1)) +
  labs(x = NULL,
       y = "Anzahl der Abgeordneten") +
  theme_minimal_hgrid(
    color = "transparent"
  ) +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 11),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
    plot.background = element_rect("#F0F0F0"),
    #aspect.ratio = 6*0.618/6
    ) +
  
  
  
  # labels
  geom_label(
    label="alle Abgeordnete", 
    x = 23,
    y = 746,
    size = 5,
    label.padding = unit(0.35, "lines"),
    label.r = unit(0.25, "lines"),
    label.size = 0.35,
    color = "black",
    fill="#F0F0F0") +
  geom_label(
    label="männliche Abgeordnete", 
    x = 24.5,
    y = 490,
    size = 5,
    label.padding = unit(0.35, "lines"),
    label.r = unit(0.25, "lines"),
    label.size = 0.35,
    color = "#E62200",
    fill="#F0F0F0") +
  geom_label(
    label="weibliche Abgeordnete", 
    x = 25,
    y = 276,
    size = 5,
    label.padding = unit(0.35, "lines"),
    label.r = unit(0.25, "lines"),
    label.size = 0.35,
    color = "#FFB813",
    fill="#F0F0F0") +
  
  
  # weitere labels
  
    geom_label(
    label="28 \nlediglich 7 % Frauen im Bundestag", 
    x = 0,
    y = 150,
    size = 4,
    color = "#FFB813",
    fill= "#F0F0F0",
    vjust = 1,
    hjust = 0) +
  
    geom_label(
    label="256 \n35 % unserer Abgeordneten sind Frauen!", 
    x = 20,
    y = 150,
    size = 4,
    color = "#FFB813",
    fill= "#F0F0F0",
    vjust = 0,
    hjust = 0) +
  expand_limits(x = c(0, 30)) +
  NULL

```

# aktueller Bundestag
```{r}

partei <- c("SPD", "CDU/CSU", "Bündnis 90/Die Grünen", "FDP", "AfD", "Die Linke", "fraktionslos")

sitze <- c(206, 197, 118, 92, 80, 39, 4)

sitze_w <- c(86, 46, 70, 23, 11, 21, 0)

sitze_m <- c(120, 151, 48, 69, 69, 18, 4)

farben <- c("#E3000F", "#000000", "#64A12D", "#ffed00", "#009EE0", "#E90098", "#737373")

order <- c(6, 3, 5, 4, 2, 7, 1)

ds <- data.frame(partei, sitze, sitze_w, sitze_m, farben, order)


reihenfolge_sitze <- c("fraktionslos", "Die Linke", "AfD", "FDP", "Bündnis 90/Die Grünen", "CDU/CSU", "SPD")
reihenfolge_sitze_umgekehrt <- c("SPD", "CDU/CSU", "Bündnis 90/Die Grünen", "FDP", "AfD", "Die Linke", "fraktionslos")
reihenfolge_w <- c("fraktionslos", "AfD", "Die Linke", "FDP", "CDU/CSU", "Bündnis 90/Die Grünen", "SPD")

farben_sitze <- c("#737373", "#E90098", "#009EE0", "#ffed00", "#64A12D", "#000000", "#E3000F")
farben_sitze_umgekehrt <- c("#E3000F", "#000000", "#64A12D", "#ffed00", "#009EE0", "#E90098", "#737373")


f <- ds %>% filter(partei != "fraktionslos")
d <- ds %>% filter(partei == "SPD")

```


```{r, layout="l-body-outset", fig.width=9, fig.height=9*0.618}
bt <- parliament_data(election_data = ds,
                      parl_rows = 15,
                      type = "semicircle",
                      party_seats = ds$sitze,
                      plot_order = ds$order)

bt %>% 
  ggplot() +
  aes(x, y, color = partei) +
  geom_parliament_seats(size = 1.6) +
  draw_partylabels(type = "semicircle",
                   party_names = partei,
                   party_seats = sitze,
                   party_colours = farben) +
  draw_totalseats(n = 736,
                  type = "semicircle", 
                  size = 8) +
  scale_color_manual(values = bt$farben,
                     limits = bt$partei) +
  theme_ggparliament(legend = T) +
   theme(
    legend.title = element_blank(),
    legend.text = element_text(size = 15),
    plot.background = element_rect("white") ##F0F0F0
  
    ) +
  coord_fixed(xlim = c(-3, 3), ylim = c(-1, 3))

```

# Frauenanteil in den Parteien

```{r}

# https://www.tagesschau.de/inland/btw21/bundestag-frauen-101.html
# https://www.dw.com/de/kritik-am-niedrigen-frauenanteil-im-neuen-bundestag/a-59342271

# quelle: https://www.bundestag.de/parlament/plenum/sitzverteilung_20wp


#ich brauche partei und sitze

partei <- c("SPD", "CDU/CSU", "Bündnis 90/Die Grünen", "FDP", "AfD", "Die Linke", "fraktionslos")

sitze <- c(206, 197, 118, 92, 80, 39, 4)

sitze_w <- c(86, 46, 70, 23, 11, 21, 0)

sitze_m <- c(120, 151, 48, 69, 69, 18, 4)

farben <- c("#E3000F", "#000000", "#64A12D", "#ffed00", "#009EE0", "#E90098", "#737373")

order <- c(6, 3, 5, 4, 2, 7, 1)

ds <- data.frame(partei, sitze, sitze_w, sitze_m, farben, order)


reihenfolge_sitze <- c("fraktionslos", "Die Linke", "AfD", "FDP", "Bündnis 90/Die Grünen", "CDU/CSU", "SPD")
reihenfolge_sitze_umgekehrt <- c("SPD", "CDU/CSU", "Bündnis 90/Die Grünen", "FDP", "AfD", "Die Linke", "fraktionslos")
reihenfolge_w <- c("fraktionslos", "AfD", "Die Linke", "FDP", "CDU/CSU", "Bündnis 90/Die Grünen", "SPD")

farben_sitze <- c("#737373", "#E90098", "#009EE0", "#ffed00", "#64A12D", "#000000", "#E3000F")
farben_sitze_umgekehrt <- c("#E3000F", "#000000", "#64A12D", "#ffed00", "#009EE0", "#E90098", "#737373")


f <- ds %>% filter(partei != "fraktionslos")
d <- ds %>% filter(partei == "SPD")

ds %>% 
  ggplot() +
  geom_vline(xintercept = 0, size = 0.3, alpha = 0.3) +
  geom_vline(xintercept = 50, size = 0.3, alpha = 0.3) +
  geom_vline(xintercept = 100, size = 0.3, alpha = 0.3) +
  geom_vline(xintercept = 150, size = 0.3, alpha = 0.3) +
  geom_vline(xintercept = 200, size = 0.3, alpha = 0.3) +
  geom_vline(xintercept = 250, size = 0.3, alpha = 0.3) +
 
  geom_col(
    aes(x = sitze, y = fct_relevel(partei, reihenfolge_sitze)),
    fill = "#737373"
  ) +
  geom_col(
    aes(x = sitze_w, y = partei),
    fill = c("#E3000F", "#000000", "#64A12D", "#ffed00", "#009EE0", "#E90098", "#737373")
  ) + 
  labs(x = NULL, y = NULL) +
  scale_x_continuous(
    limits = c(0, 250),
    breaks = c(0, 50, 100, 150, 200, 250),
    expand = c(0,3)) +
  labs(x = NULL, y = NULL) +
  theme_minimal_hgrid(
    color = "transparent"
  ) +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 11),
    plot.background = element_rect("#F0F0F0"),
    aspect.ratio = 6*0.618/6
    ) +
  geom_text(data = f, aes(x = sitze_w, y = partei, label = sitze_w), hjust = -1.2, color = "black") +
  geom_text(aes(x = sitze, y = partei, label = sitze), hjust = -1.2, color = "black")


```


